package com.maomao.ssm.dao;

import com.maomao.ssm.bean.UserFeedback;
import com.maomao.ssm.bean.UserFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    long countByExample(UserFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    int deleteByExample(UserFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    int insert(UserFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    int insertSelective(UserFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    List<UserFeedback> selectByExample(UserFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    UserFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserFeedback record, @Param("example") UserFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    int updateByExample(@Param("record") UserFeedback record, @Param("example") UserFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    int updateByPrimaryKeySelective(UserFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbg.generated Fri Jan 26 13:55:48 CST 2018
     */
    int updateByPrimaryKey(UserFeedback record);
}